In [2]:
import torch
import numpy as np

In [3]:
def describe(x):
    print('Type: {}'.format(x.type()))
    print('Shape/size: {}'.format(x.shape))
    print('Values: \n{}'.format(x))

In [4]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.4196e+22, 3.0747e-41, 1.5695e-43],
        [1.5554e-43, 1.5975e-43, 1.6255e-43]])


In [5]:
describe(torch.rand(2, 3))
describe(torch.randn(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5229, 0.0474, 0.4979],
        [0.9940, 0.2311, 0.6441]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.6178, -0.5954, -0.3141],
        [-0.6488,  1.3055, -0.5241]])


In [6]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [7]:
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.8818, 0.4666, 0.5991],
        [0.7672, 0.3760, 0.4746]], dtype=torch.float64)


In [10]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [14]:
x = torch.rand(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2148, 0.6728, 0.1665],
        [0.5331, 0.9159, 0.6148]])


In [15]:
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.4296, 1.3456, 0.3329],
        [1.0663, 1.8317, 1.2296]])


In [16]:
describe(x + x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.4296, 1.3456, 0.3329],
        [1.0663, 1.8317, 1.2296]])


In [19]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [20]:
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [21]:
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [22]:
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [23]:
describe(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [3]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
describe(x[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [26]:
describe(x[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [27]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [4]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [5]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


In [17]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [18]:
describe(torch.cat([x, x], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [20]:
describe(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [21]:
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [22]:
x1 = torch.arange(6).view(2, 3)
describe(x1)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [23]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [25]:
describe(torch.mm(x1.float(), x2.float()))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


# Tensor & Computational Graph

In [26]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [27]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [28]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


In [32]:
print(torch.cuda.is_available())

False


# Exercise

In [36]:
# 1. Building 2D Tensor, Embedding dim 1 to dim 0
x = torch.arange(4).view(2, 2)
x.unsqueeze(0)

tensor([[[0, 1],
         [2, 3]]])

In [37]:
# 2. Delete the tensor before
x.squeeze(0)

tensor([[0, 1],
        [2, 3]])

In [4]:
# 3. use [3, 7) to build tensor by 5 x 3
3 + torch.rand(5, 3) * (7 - 3)

tensor([[6.1352, 4.6810, 5.0550],
        [5.9248, 3.5772, 4.2357],
        [5.6417, 3.3799, 3.7168],
        [4.0108, 6.2316, 5.3124],
        [4.2140, 4.8278, 3.8585]])

In [5]:
# 4. build normal distribution (mean = 0, std = 1) tensor
a = torch.rand(3, 3)
a.normal_()

tensor([[ 0.1415,  0.1836, -1.3808],
        [ 0.6105,  0.1518,  0.3001],
        [ 0.4909, -0.8304,  1.6510]])

In [6]:
# 5. read no zero index in torch.Tensor([1, 1, 1, 0, 1])
a = torch.Tensor([1, 1, 1, 0, 1])
a.nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

In [7]:
# 6. build a tensor with (3, 1), and add 4 copy with horizontal
a = torch.rand(3, 1)
a.expand(3, 4)

tensor([[0.6093, 0.6093, 0.6093, 0.6093],
        [0.4799, 0.4799, 0.4799, 0.4799],
        [0.9624, 0.9624, 0.9624, 0.9624]])

In [8]:
# 7. return 2 3D matrix(a=torch.rand(3,4,5), b=torch.rand(3,5,4)) batch matrix-matrix product
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)
torch.bmm(a, b)

tensor([[[1.3047, 1.3369, 1.7047, 1.4653],
         [1.2709, 0.9456, 1.2777, 1.1373],
         [0.8455, 0.5640, 0.9625, 0.6749],
         [1.1237, 1.2670, 1.5938, 1.3493]],

        [[0.9528, 1.8215, 1.3130, 1.3826],
         [0.6811, 1.0752, 0.8783, 0.8011],
         [0.9984, 1.2119, 0.7897, 1.0236],
         [1.1187, 1.1647, 0.6850, 1.0198]],

        [[0.3310, 0.4668, 0.6041, 0.5403],
         [0.6172, 1.7551, 1.2554, 2.0506],
         [0.2725, 0.9518, 1.1502, 1.1850],
         [1.0102, 1.5743, 1.3501, 1.4748]]])

In [9]:
# 8. return 3D matrix and 2D matrix(a=torch.rand(3,4,5), b=torch.rand(5,4)) batch matrix-matrix product
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.0780, 0.5880, 1.1208, 0.5199],
         [0.7087, 0.9705, 0.7609, 0.5722],
         [1.8855, 1.4909, 1.7448, 0.5693],
         [0.9250, 1.2132, 0.9778, 0.6726]],

        [[1.5788, 1.0772, 1.5923, 0.6525],
         [2.0631, 1.7376, 2.1345, 1.0466],
         [1.0668, 1.2330, 1.1518, 0.5898],
         [1.2879, 1.6284, 1.3394, 1.0412]],

        [[1.1780, 1.6986, 1.1047, 0.8643],
         [1.7058, 1.9723, 1.5695, 0.9614],
         [1.8471, 1.5113, 1.6885, 0.7277],
         [1.2187, 0.9870, 1.2070, 0.5300]]])